import sys
import json
import random
import re

def slugify(text):
    text = re.sub(r'[^\w\s-]', '', text.lower())
    return re.sub(r'\s+', '_', text.strip())[:30]

def generate_content(topic, gen_type="report"):
    topic_clean = topic.strip()
    if not topic_clean:
        topic_clean = "Research Topic"
        
    gen_type = gen_type.lower()
    slug = slugify(topic_clean)
    filename = f"{gen_type}_{slug}.pdf"
    
    # Base fragments for deterministic assembly
    fragments = {
        "overview": [
            f"{topic_clean} represents a critical junction in modern technical evolution.",
            f"The primary focus of {topic_clean} remains its impact on scalability and efficiency.",
            f"Recent deployments of {topic_clean} demonstrate significant shifts in operational methodology."
        ],
        "key_drivers": [
            f"Advancements in {topic_clean} are primarily catalyzed by increased data availability.",
            f"Cross-functional integration is the leading trend within the {topic_clean} ecosystem.",
            f"Sustainability has become a non-negotiable driver for {topic_clean} innovation."
        ],
        "risks": [
            f"Security vulnerabilities in {topic_clean} frameworks remain a primary concern for stakeholders.",
            f"Latency issues during high-load scenarios can impact the reliability of {topic_clean}.",
            f"Interoperability conflicts between legacy systems and {topic_clean} modules often arise."
        ],
        "insights": [
            f"The pivot towards {topic_clean} indicates a long-term commitment to digital resilience.",
            f"Architectural modularity is the most sustainable approach to scaling {topic_clean}.",
            f"Data-driven decision making is now the standard for {topic_clean} lifecycle management."
        ]
    }

    result = {
        "filename": filename,
        "title": f"{gen_type.capitalize()}: {topic_clean}",
        "sections": [],
        "footer_note": f"Structured {gen_type.capitalize()} Generated by Semantic Engine V2"
    }

    if gen_type == "report":
        result["sections"] = [
            {
                "heading": "Abstract & Overview",
                "content": random.choice(fragments["overview"]) + " " + random.choice(fragments["insights"])
            },
            {
                "heading": "Current Trends & Drivers",
                "content": random.choice(fragments["key_drivers"]),
                "bullets": [
                    f"Structural optimization of {topic_clean} protocols.",
                    f"Rapid integration of {topic_clean} in localized environments.",
                    f"Increased emphasis on {topic_clean} security standards."
                ]
            },
            {
                "heading": "Critical Risks & Challenges",
                "content": random.choice(fragments["risks"]),
                "bullets": [
                    f"Resource constraints during {topic_clean} scaling.",
                    f"Compatibility bottlenecks with existing {topic_clean} infrastructure.",
                    f"Dynamic threat landscapes targeting {topic_clean} nodes."
                ]
            }
        ]
    elif gen_type == "summary":
        result["sections"] = [
            {
                "heading": "Executive Summary",
                "content": f"A high-level synthesis of {topic_clean} dynamics and its strategic implications."
            },
            {
                "heading": "Essential Takeaways",
                "bullets": [
                    f"{topic_clean} is a prerequisite for modern competitive positioning.",
                    f"Efficiency gains from {topic_clean} often exceed {random.randint(25, 60)}%.",
                    f"Future-proofing depends on the modularity of {topic_clean} stacks."
                ]
            },
            {
                "heading": "Operational Conclusion",
                "content": f"The long-term viability of {topic_clean} is contingent on continuous architectural refinement."
            }
        ]
    else: # notes
        result["sections"] = [
            {
                "heading": "Contextual Background",
                "content": f"Brief notes on the foundational elements of {topic_clean} and its recent shifts."
            },
            {
                "heading": "Detailed Breakdown",
                "bullets": [
                    f"Phase 1: Initial assessment of {topic_clean} requirements.",
                    f"Phase 2: Tactical deployment of core {topic_clean} modules.",
                    f"Phase 3: Performance monitoring and {topic_clean} optimization."
                ]
            },
            {
                "heading": "Actionable Insights",
                "content": random.choice(fragments["insights"]),
                "bullets": [
                    f"Prioritize {topic_clean} stability over feature expansion.",
                    f"Regularly audit {topic_clean} for security compliance.",
                    f"Document all {topic_clean} config changes instantly."
                ]
            }
        ]
        
    return result

if __name__ == "__main__":
    try:
        topic = sys.argv[1] if len(sys.argv) > 1 else "General Technology"
        gen_type = sys.argv[2] if len(sys.argv) > 2 else "report"
        data = generate_content(topic, gen_type)
        print(json.dumps(data))
    except Exception as e:
        print(json.dumps({"error": str(e)}), file=sys.stderr)
        sys.exit(1)
