import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';
import { exec } from 'child_process';
import path from 'path';
import util from 'util';

const execAsync = util.promisify(exec);

async function buildPDF(content) {
    const pdfDoc = await PDFDocument.create();
    const timesRomanFont = await pdfDoc.embedFont(StandardFonts.TimesRoman);
    const timesRomanBoldFont = await pdfDoc.embedFont(StandardFonts.TimesRomanBold);
    
    let page = pdfDoc.addPage([612, 792]);
    const { width, height } = page.getSize();
    let yPosition = height - 70;
    const margin = 50;
    const maxWidth = width - (margin * 2);
    const lineHeight = 16;
    
    const wrapText = (text, font, size, maxWidth) => {
        const words = text.split(' ');
        const lines = [];
        let currentLine = '';
        
        for (const word of words) {
            const testLine = currentLine ? `${currentLine} ${word}` : word;
            const textWidth = font.widthOfTextAtSize(testLine, size);
            if (textWidth > maxWidth) {
                if (currentLine) lines.push(currentLine);
                currentLine = word;
            } else {
                currentLine = testLine;
            }
        }
        if (currentLine) lines.push(currentLine);
        return lines;
    };
    
    const checkPageBreak = (spaceNeeded) => {
        if (yPosition < spaceNeeded) {
            page = pdfDoc.addPage([612, 792]);
            yPosition = height - 70;
        }
    };

    // Title
    page.drawText(content.title, { x: margin, y: yPosition, size: 24, font: timesRomanBoldFont, color: rgb(0.1, 0.2, 0.4) });
    yPosition -= 40;
    
    // Summary
    const summaryLines = wrapText(content.summary, timesRomanFont, 12, maxWidth);
    for (const line of summaryLines) {
        page.drawText(line, { x: margin, y: yPosition, size: 12, font: timesRomanFont, color: rgb(0.3, 0.3, 0.3) });
        yPosition -= lineHeight;
    }
    yPosition -= 20;
    
    // Sections
    for (const section of content.sections) {
        checkPageBreak(80);
        page.drawText(section.heading, { x: margin, y: yPosition, size: 16, font: timesRomanBoldFont, color: rgb(0.1, 0.2, 0.4) });
        yPosition -= 25;
        
        const contentLines = wrapText(section.content, timesRomanFont, 11, maxWidth);
        for (const line of contentLines) {
            checkPageBreak(40);
            page.drawText(line, { x: margin, y: yPosition, size: 11, font: timesRomanFont, color: rgb(0, 0, 0) });
            yPosition -= lineHeight;
        }
        yPosition -= 15;
    }
    
    // Facts
    checkPageBreak(100);
    page.drawText('Key Findings & Metrics', { x: margin, y: yPosition, size: 16, font: timesRomanBoldFont, color: rgb(0.1, 0.2, 0.4) });
    yPosition -= 25;
    
    for (const fact of content.facts) {
        const factLines = wrapText(`• ${fact}`, timesRomanFont, 11, maxWidth - 10);
        for (const line of factLines) {
            checkPageBreak(40);
            page.drawText(line, { x: margin + 10, y: yPosition, size: 11, font: timesRomanFont, color: rgb(0.2, 0.2, 0.2) });
            yPosition -= lineHeight;
        }
        yPosition -= 10;
    }
    
    // Footer
    page.drawText('Generated by AI Research Report Generator', {
        x: margin, y: 30, size: 9, font: timesRomanFont, color: rgb(0.5, 0.5, 0.5)
    });
    
    return await pdfDoc.save();
}

export default async function handler(req, res) {
    if (req.method !== 'POST') {
        return res.status(405).json({ error: 'Method not allowed. Use POST.' });
    }
    
    const { topic } = req.body;
    if (!topic || typeof topic !== 'string' || topic.trim().length === 0) {
        return res.status(400).json({ error: 'Topic is required and must be a non-empty string' });
    }
    
    try {
        const pythonScript = path.join(process.cwd(), 'utils', 'content_engine.py');
        const { stdout, stderr } = await execAsync(`python3 "${pythonScript}" "${topic.trim()}"`);
        
        const aiContent = JSON.parse(stdout);
        const pdfBytes = await buildPDF(aiContent);
        
        res.setHeader('Content-Type', 'application/pdf');
        res.setHeader('Content-Disposition', `attachment; filename="${aiContent.filename}"`);
        res.setHeader('Content-Length', pdfBytes.length);
        
        return res.status(200).send(Buffer.from(pdfBytes));
    } catch (error) {
        console.error('PDF generation error:', error);
        return res.status(500).json({ error: 'Failed to generate PDF. Check server logs.' });
    }
}
